# Generated by Django 3.0.7 on 2020-06-06 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 6, 15, 11, 48, 357397, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
