# Generated by Django 3.0.7 on 2020-06-06 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_profile_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='webapps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('main_picture', models.ImageField(default='media/webapps/internet.png', upload_to='webapps/')),
                ('screenshot1', models.ImageField(blank=True, default='media/webapps/internet.png', upload_to='webapps/')),
                ('screenshot2', models.ImageField(blank=True, default='media/webapps/internet.png', upload_to='webapps/')),
                ('link', models.TextField()),
                ('description', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
