# Generated by Django 3.0.7 on 2020-06-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200607_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapps',
            name='screenshot3',
            field=models.ImageField(blank=True, default='media/webapps/internet.png', upload_to='webapps/'),
        ),
    ]
