# Generated by Django 3.0.7 on 2020-06-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='webapp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.webapps'),
        ),
    ]
