# Generated by Django 3.0.7 on 2020-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200608_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='average',
            field=models.IntegerField(default=0),
        ),
    ]
