# Generated by Django 3.0.7 on 2020-06-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_ratings_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='average',
        ),
    ]
